#ifndef CONTROLSTIPARAM_GLOBAL_H
#define CONTROLSTIPARAM_GLOBAL_H



#if defined(CONTROLSTIPARAM_LIBRARY)
#  define CONTROLSTIPARAM_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLSTIPARAM_EXPORT Q_DECL_IMPORT
#endif



#endif // CONTROLSTIPARAM_GLOBAL_H
